# permissions for end users to edit fetchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fetcher-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: scget
    app.kubernetes.io/part-of: scget
    app.kubernetes.io/managed-by: kustomize
  name: fetcher-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - fetchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - fetchers/status
  verbs:
  - get
